In [5]:
import numpy as np  
a = np.array([1,2,3,'4'])
print(a,a.dtype)

a = np.array([2,3,4],dtype=np.uint32)
b = np.array([5,6,7],dtype=np.uint32)
c_unsigned32 = a-b
print('unsined c:',c_unsigned32,c_unsigned32.dtype)
c_signed32 = a-b.astype(np.int32)
print('singed c: ',c_signed32,c_signed32.dtype)

['1' '2' '3' '4'] <U21
unsined c: [4294967293 4294967293 4294967293] uint32
singed c:  [-3 -3 -3] int64
4294967295


In [6]:
import numpy as np
print(np.arange(10))
print(np.arange(2, 10, dtype=float))
print(np.arange(2,3,0.1))
print(np.linspace(1.,4.,6))

[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[1.  1.6 2.2 2.8 3.4 4. ]


In [17]:
import numpy as np
print(np.eye(3))
print(np.eye(3,5))

print(np.diag([1,2,3]))
print(np.diag([1,2,3],1))

a = np.array([[1,2],[3,4]])
print(np.diag(a))

print(np.vander(np.linspace(0,2,5),2))
print(np.vander([1,2,3,4],2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[1 4]
[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]
[[1 1]
 [2 1]
 [3 1]
 [4 1]]


In [21]:
import numpy as np
np.zeros((2,3))
np.zeros((2,3,2))

np.ones((2,3))
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
import numpy as np
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [23]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [30]:
a = np.array([1,2,3,4,5,6])
b = a[:2]
b+=1
print('a:',a)
print('b:',b)

a: [2 3 3 4 5 6]
b: [2 3]


In [31]:
a = np.array([1,2,3,4])
b = a[:2].copy()
b+=1
print('a=',a,'b=',b)

a= [1 2 3 4] b= [2 3]


In [34]:
A = np.ones((2,2))
B = np.eye(2,2)
C = np.zeros((2,2))
D = np.diag((-3,-4))
print(A)
print(B)
print(C)
print(D)
np.block([[A,B],[C,D]])

[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[-3  0]
 [ 0 -4]]


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [37]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [38]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
import numpy as np
s = io.StringIO("1,2,3\n4,,6\n7,8,9")
print(np.genfromtxt(s, delimiter=','))
print(s.seek(0))

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
0


In [57]:
x = np.arange(1,25).reshape(2,4,3)
print(x[[True, False]])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


## Example: Multi-dimensional vs. chained indexing in NumPy
This example demonstrates the difference between using `x[0,1,2]` and `x[0][1][2]` on a 3D NumPy array.

In [ ]:
import numpy as np
x = np.arange(27).reshape(3, 3, 3)
print("Array x:\n", x)
print("x[0,1,2] =", x[0,1,2])
print("x[0][1][2] =", x[0][1][2])
print('x[x%2==0]',x[x%2==0])


Array x:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
x[0,1,2] = 5
x[0][1][2] = 5
x[x%2==0] [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26]
x[[True, False, False]] [[[0 1 2]
  [3 4 5]
  [6 7 8]]]


Both `x[0,1,2]` and `x[0][1][2]` return the same value for this case, but `x[0,1,2]` is the preferred and more efficient way in NumPy. For regular Python lists, only chained indexing works.

## Timing the difference between multi-dimensional and chained indexing in NumPy
This example measures the time taken by `x[0,1,2]` vs. `x[0][1][2]` for a large number of accesses.

In [49]:
import numpy as np
import time

x = np.arange(1000000).reshape(100, 100, 100)

# Multi-dimensional indexing
t0 = time.time()
for _ in range(1000000):
    y = x[10,20,30]
time_multi = time.time() - t0

# Chained indexing
t0 = time.time()
for _ in range(1000000):
    y = x[10][20][30]
time_chained = time.time() - t0

print(f"Multi-dimensional indexing: {time_multi:.4f} seconds")
print(f"Chained indexing: {time_chained:.4f} seconds")

Multi-dimensional indexing: 0.1507 seconds
Chained indexing: 0.3149 seconds


You will see that multi-dimensional indexing (`x[10,20,30]`) is faster than chained indexing (`x[10][20][30]`) in NumPy.

In [77]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.sum())              # 전체 합
print(a.mean(axis=0))       # 열 평균
print(a.mean(axis=1))       # 행 평균
print(a.max(axis=0))        # 각 열의 최대값
print(a.max(axis=1))        # 각 행의 최대값
print(a.min())              # 전체 최소값
print(a.std())              # 표준편차
np.max(a, where=(a < 6), initial=-999999)

21
[2.5 3.5 4.5]
[2. 5.]
[4 5 6]
[3 6]
1
1.707825127659933


np.int64(5)

# Pandas

## Data Structure

- Series : 1차원 라벨이 있는 배열의 데이터 구조
    - index : Hashable하면서 Data와 같은 길이
- DataFrame : 2차원의 라벨 데이터구조

In [88]:
import pandas as pd 
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 30, 35],'City': ['New York', 'Los Angeles', 'Chicago']},index=['A', 'B', 'C'])
print(df)

df.columns
df.index
y = df.iloc[0]
x = df.loc['B']
type(y)
print(y)
print()
print(x)

      Name  Age         City
A    Alice   25     New York
B      Bob   30  Los Angeles
C  Charlie   35      Chicago
Name       Alice
Age           25
City    New York
Name: A, dtype: object

Name            Bob
Age              30
City    Los Angeles
Name: B, dtype: object


# Copy parameter, index 변경 예시

In [1]:
import numpy as np
import pandas as pd
a = [1,2,3]
na = np.array(a)
s = pd.Series(na)
s.iloc[0] = 99
print(na)

s= pd.Series(na, copy=True)
s.iloc[0] = 100
print(na)
print('s:',s)

s = pd.Series(a)
s.iloc[0] = 101
print(a)

print(s)


[99  2  3]
[99  2  3]
s: 0    100
1      2
2      3
dtype: int64
[1, 2, 3]
0    101
1      2
2      3
dtype: int64


# Indexing / Selection

|작업|예시|
|---|---|
|인덱스로 선택 | s.iloc[0]|
|인덱스로 slice | s.iloc[5:10]|
|Index Array로 slice | s.iloc[[2,3]]|
|Label로 선택 | s["a"]|
|Label로 slice | s["b":"d"]|
|Boolean Vector로 선택 | s[bool_vec]|
|Dict-like| "b" in s, s.get("C")|

# Vectorizatino and Label alignment

In [ ]:
s+s
s*2

0    202
1      4
2      6
dtype: int64

In [4]:
s.iloc[1:] + s.iloc[:-1]

0    NaN
1    4.0
2    NaN
dtype: float64

# DataFrame


In [ ]:
## Dict input
d = {"one":pd.Series([1.0, 2.0, 3.0], index=["a","b","c"]),"two":pd.Series([1.0,2.0,3.0,4.0], index=["a","b","c","d"])}
pd.DataFrame(d)


one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [7]:
pd.DataFrame(d, index=["d","b","a"])

one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [ ]:
pd.DataFrame(d, columns=["two","three"])

two three
a  1.0   NaN
b  2.0   NaN
c  3.0   NaN
d  4.0   NaN

In [9]:
# dict안의 list의 길이가 서로 다름
d = {"one":[1.0,2.0,3.0],"two":[1.0,2.0,3.0,4.0]}
pd.DataFrame(d)

ValueError: All arrays must be of the same length

In [ ]:
#index의 길이가 dict안의 list의 길이와 다름
d = {"one":[1.0,2.0,3.0,4.0],"two":[4.0,3.0,2.0]}
pd.DataFrame(d, index=["a","b","c"])

ValueError: Length of values (4) does not match length of index (3)

In [ ]:
## List of dict input
d = [{"a":1, "b":2},{"a":5, "b":10, "c":20}]
pd.DataFrame(d)

a   b     c
0  1   2   NaN
1  5  10  20.0

In [ ]:
## Column의 선택, 추가 , 삭제
### DataFrame을 Series의 Dict 처럼 다룰 수 있다.
df = pd.DataFrame({"one":[1.0,2.0,3.0,4.0],"two":[4.0,3.0,2.0,1.0]}, index=["a","b","c","d"])

### Label로 Column을 선택
df["one"]

### dict의 key에 value를 할당하듯, 새로운 column을 추가
df["three"] = df['one']*2
df["flag"] = df["one"] > 2

### del, pop으로 column 삭제
del df["two"]
three = df.pop("three")

### insert로 위치를 지정하여 추가
df.insert(1, "one_trunc", df["one"][:2])